 language: node_js
 node_js:
   - "4.1"
 before_script:
   - chmod +x ./node_modules/.bin/gulp
 install: npm install
 script: gulp
 after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
